-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-04-05 16:44:44 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE dokument (
    dokument_id      INTEGER NOT NULL,
    nazev            VARCHAR2(255) NOT NULL,
    soubor           BLOB NOT NULL,
    typ_obsahu       VARCHAR2(50) NOT NULL,
    zprava_id_zprava INTEGER NOT NULL
);

ALTER TABLE dokument ADD CONSTRAINT dokument_pk PRIMARY KEY ( dokument_id );

CREATE TABLE fyzicka_schuzka (
    id_schuzka INTEGER NOT NULL,
    umisteni   VARCHAR2(200) NOT NULL
);

ALTER TABLE fyzicka_schuzka ADD CONSTRAINT fyzicka_schuzka_pk PRIMARY KEY ( id_schuzka );

CREATE TABLE kontakt (
    id_kontakt       INTEGER NOT NULL,
    jmeno            VARCHAR2(100) NOT NULL,
    stredni_jmeno    VARCHAR2(100),
    prijmeni         VARCHAR2(100) NOT NULL,
    telefonni_cislo  VARCHAR2(15),
    email            VARCHAR2(255),
    popis            VARCHAR2(2000),
    zprava_id_zprava INTEGER NOT NULL
);

ALTER TABLE kontakt ADD CONSTRAINT kontakt_pk PRIMARY KEY ( id_kontakt );

CREATE TABLE online_schuzka (
    id_schuzka INTEGER NOT NULL,
    odkaz      VARCHAR2(2048) NOT NULL
);

ALTER TABLE online_schuzka ADD CONSTRAINT online_schuzka_pk PRIMARY KEY ( id_schuzka );

CREATE TABLE opatreni (
    opatreni_id      INTEGER NOT NULL,
    popis            VARCHAR2(2000) NOT NULL,
    zprava_id_zprava INTEGER NOT NULL,
    naklady          INTEGER
);

ALTER TABLE opatreni ADD CONSTRAINT opatreni_pk PRIMARY KEY ( opatreni_id );

CREATE TABLE pobocka (
    id_pobocka INTEGER NOT NULL,
    nazev      VARCHAR2(100) NOT NULL,
    umisteni   VARCHAR2(200) NOT NULL
);

ALTER TABLE pobocka ADD CONSTRAINT pobocka_pk PRIMARY KEY ( id_pobocka );

CREATE TABLE prava (
    id_prava INTEGER NOT NULL,
    nazev    VARCHAR2(10) NOT NULL
);

ALTER TABLE prava ADD CONSTRAINT prava_pk PRIMARY KEY ( id_prava );

CREATE TABLE schuzka (
    id_schuzka       INTEGER NOT NULL,
    cas_zacatek      TIMESTAMP NOT NULL,
    cas_konec        TIMESTAMP NOT NULL,
    popis            VARCHAR2(2000),
    zprava_id_zprava INTEGER NOT NULL,
    typ_schuzky      VARCHAR2(15) NOT NULL
);

ALTER TABLE schuzka
    ADD CONSTRAINT ch_inh_schuzka CHECK ( typ_schuzky IN ( 'fyzicka_schuzka', 'online_schuzka', 'schuzka' ) );

ALTER TABLE schuzka ADD CONSTRAINT schuzka_pk PRIMARY KEY ( id_schuzka );

CREATE TABLE schuzka_uzivatel (
    schuzka_id_schuzka   INTEGER NOT NULL,
    uzivatel_id_uzivatel INTEGER NOT NULL
);

ALTER TABLE schuzka_uzivatel ADD CONSTRAINT schuzka_uzivatel_pk PRIMARY KEY ( schuzka_id_schuzka,
                                                                              uzivatel_id_uzivatel );

CREATE TABLE tema (
    id_tema INTEGER NOT NULL,
    nazev   VARCHAR2(50) NOT NULL
);

ALTER TABLE tema ADD CONSTRAINT tema_pk PRIMARY KEY ( id_tema );

CREATE TABLE uzivatel (
    id_uzivatel        INTEGER NOT NULL,
    jmeno              VARCHAR2(100) NOT NULL,
    stredni_jmeno      VARCHAR2(100),
    prijmeni           VARCHAR2(100) NOT NULL,
    email              VARCHAR2(100) NOT NULL,
    heslo              VARCHAR2(128) NOT NULL,
    telefonni_cislo    VARCHAR2(15),
    pobocka_id_pobocka INTEGER NOT NULL,
    prava_id_prava     INTEGER NOT NULL
);

ALTER TABLE uzivatel ADD CONSTRAINT uzivatel_pk PRIMARY KEY ( id_uzivatel );

ALTER TABLE uzivatel ADD CONSTRAINT uzivatel_email_un UNIQUE ( email );

CREATE TABLE zpetna_vazba (
    id_zpetna_vazba      INTEGER NOT NULL,
    zpetna_vazba         VARCHAR2(2000) NOT NULL,
    zprava_id_zprava     INTEGER NOT NULL,
    uzivatel_id_uzivatel INTEGER NOT NULL
);

ALTER TABLE zpetna_vazba ADD CONSTRAINT zpetna_vazba_pk PRIMARY KEY ( id_zpetna_vazba );

CREATE TABLE zprava (
    id_zprava            INTEGER NOT NULL,
    titulek              VARCHAR2(100) NOT NULL,
    popisek              VARCHAR2(2000),
    uzavreno             TIMESTAMP,
    vytvoreno            TIMESTAMP NOT NULL,
    upraveno             TIMESTAMP NOT NULL,
    uzivatel_id_uzivatel INTEGER NOT NULL,
    tema_id_tema         INTEGER NOT NULL
);

ALTER TABLE zprava ADD CONSTRAINT zprava_pk PRIMARY KEY ( id_zprava );

ALTER TABLE dokument
    ADD CONSTRAINT dokument_zprava_fk FOREIGN KEY ( zprava_id_zprava )
        REFERENCES zprava ( id_zprava )
            ON DELETE CASCADE;

ALTER TABLE fyzicka_schuzka
    ADD CONSTRAINT fyzicka_schuzka_schuzka_fk FOREIGN KEY ( id_schuzka )
        REFERENCES schuzka ( id_schuzka );

ALTER TABLE kontakt
    ADD CONSTRAINT kontakt_zprava_fk FOREIGN KEY ( zprava_id_zprava )
        REFERENCES zprava ( id_zprava )
            ON DELETE CASCADE;

ALTER TABLE online_schuzka
    ADD CONSTRAINT online_schuzka_schuzka_fk FOREIGN KEY ( id_schuzka )
        REFERENCES schuzka ( id_schuzka );

ALTER TABLE opatreni
    ADD CONSTRAINT opatreni_zprava_fk FOREIGN KEY ( zprava_id_zprava )
        REFERENCES zprava ( id_zprava )
            ON DELETE CASCADE;

ALTER TABLE schuzka_uzivatel
    ADD CONSTRAINT schuzka_uzivatel_schuzka_fk FOREIGN KEY ( schuzka_id_schuzka )
        REFERENCES schuzka ( id_schuzka );

ALTER TABLE schuzka_uzivatel
    ADD CONSTRAINT schuzka_uzivatel_uzivatel_fk FOREIGN KEY ( uzivatel_id_uzivatel )
        REFERENCES uzivatel ( id_uzivatel );

ALTER TABLE schuzka
    ADD CONSTRAINT schuzka_zprava_fk FOREIGN KEY ( zprava_id_zprava )
        REFERENCES zprava ( id_zprava );

ALTER TABLE uzivatel
    ADD CONSTRAINT uzivatel_pobocka_fk FOREIGN KEY ( pobocka_id_pobocka )
        REFERENCES pobocka ( id_pobocka )
            ON DELETE CASCADE;

ALTER TABLE uzivatel
    ADD CONSTRAINT uzivatel_prava_fk FOREIGN KEY ( prava_id_prava )
        REFERENCES prava ( id_prava );

ALTER TABLE zpetna_vazba
    ADD CONSTRAINT zpetna_vazba_uzivatel_fk FOREIGN KEY ( uzivatel_id_uzivatel )
        REFERENCES uzivatel ( id_uzivatel )
            ON DELETE CASCADE;

ALTER TABLE zpetna_vazba
    ADD CONSTRAINT zpetna_vazba_zprava_fk FOREIGN KEY ( zprava_id_zprava )
        REFERENCES zprava ( id_zprava )
            ON DELETE CASCADE;

ALTER TABLE zprava
    ADD CONSTRAINT zprava_tema_fk FOREIGN KEY ( tema_id_tema )
        REFERENCES tema ( id_tema );

ALTER TABLE zprava
    ADD CONSTRAINT zprava_uzivatel_fk FOREIGN KEY ( uzivatel_id_uzivatel )
        REFERENCES uzivatel ( id_uzivatel );

CREATE OR REPLACE TRIGGER arc_fkarc_8_online_schuzka BEFORE
    INSERT OR UPDATE OF id_schuzka ON online_schuzka
    FOR EACH ROW
DECLARE
    d VARCHAR2(15);
BEGIN
    SELECT
        a.typ_schuzky
    INTO d
    FROM
        schuzka a
    WHERE
        a.id_schuzka = :new.id_schuzka;

    IF ( d IS NULL OR d <> 'online_schuzka' ) THEN
        raise_application_error(-20223, 'FK online_schuzka_schuzka_FK in Table online_schuzka violates Arc constraint on Table schuzka - discriminator column typ_schuzky doesn''t have value ''online_schuzka'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_8_fyzicka_schuzka BEFORE
    INSERT OR UPDATE OF id_schuzka ON fyzicka_schuzka
    FOR EACH ROW
DECLARE
    d VARCHAR2(15);
BEGIN
    SELECT
        a.typ_schuzky
    INTO d
    FROM
        schuzka a
    WHERE
        a.id_schuzka = :new.id_schuzka;

    IF ( d IS NULL OR d <> 'fyzicka_schuzka' ) THEN
        raise_application_error(-20223, 'FK fyzicka_schuzka_schuzka_FK in Table fyzicka_schuzka violates Arc constraint on Table schuzka - discriminator column typ_schuzky doesn''t have value ''fyzicka_schuzka'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE SEQUENCE id_kontakt_seq START WITH 1;

CREATE SEQUENCE id_opatreni_seq START WITH 1;

CREATE SEQUENCE id_zpetna_vazba_seq START WITH 1;

CREATE SEQUENCE id_zprava_seq START WITH 1;
