import type { Metadata } from 'next';
import ThemeProvider from '../components/ThemeProvider';
import QueryClientProvider from '../components/QueryClientProvider';
import { Stack } from '@mui/material';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider>
          <ThemeProvider>
            <Stack mx={5}>{children}</Stack>
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
